# BASICS OF PYTORCH

### Welcome to the notebook

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. It is free and open-source software released under the Modified BSD license.

In this notebook we will be covering basics of pytorch and five functions of pytorch namely - 
- new_ones
- function 2
- function 3
- function 4
- function 5

In [0]:
# Import torch and other required modules
import torch

##  Function 1 

##new_ones 

Returns a Tensor of size "size" filled with 1. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

In [0]:
# Example 1 
tensor = torch.tensor((), dtype = torch.float64)
tensor.new_ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

we get a tensor of size 2x3 filled with 1's.

In [0]:
# Example 2 
tensor2 = torch.tensor(() , dtype = torch.float64)
tensor2.new_ones((10,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

We get a tensor of 10x2 filled with 1's

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
tensor3 = torch.tensor(() , dtype = torch.float64)
tensor3.new_ones(10.2)

TypeError: ignored

The size argument passed in the function must be an integer.

**When to use this function**

use this function to easily initialise your tensor with 1's

## Function 2

## torch.Tensor.item()

It is used to get a python number from a tensor containing a single value.

In [0]:
# Example 1 
x = torch.tensor([5])
x.item()

5

we get output as 5 which was stored in tensor x

In [0]:
# Example 2 
x = torch.tensor(11.5)
x.item()

11.5

we get output as 11.5 which was stored in tensor x

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([11,2])
x.item()

ValueError: ignored

This function can only be used to get a python number from a tensor containing a single value

**When to use this function**

Use torch.Tensor.item() to get a Python number from a tensor containing a single value

## Function 3


## torch.autograd

A tensor can be created with requires_grad=True so that torch.autograd records operations on them for automatic differentiation.

In [0]:
# Example 1 
x = torch.tensor([5.], requires_grad=True)
y = torch.tensor([3.], requires_grad=False)#acts as a constant
b = torch.tensor([2.] , requires_grad=True)
z = x@y+b
z.backward()
print("dz/dx" , x.grad)
print("dz/dy" , y.grad)
print("dz/db" , b.grad)

dz/dx tensor([3.])
dz/dy None
dz/db tensor([1.])


autograd records the operations for automatic differnetiation.

In [0]:
# Example 2 
x = torch.tensor([5.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
b = torch.tensor([2.] , requires_grad=False)#acts as a constant
z = y*b-x
z.backward()
print("dz/dx" , x.grad)
print("dz/dy" , y.grad)
print("dz/db" , b.grad)



dz/dx tensor([-1.])
dz/dy tensor([2.])
dz/db None


autograd records the operations for automatic differnetiation.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 
# Example 1 
x = torch.tensor([5.], requires_grad=False)#acts as a constant
y = torch.tensor([3.], requires_grad=False)#acts as a constant
b = torch.tensor([2.] , requires_grad=False)#acts as a constant
z = y*b-x
z.backward()
print("dz/dx" , x.grad)
print("dz/dy" , y.grad)
print("dz/db" , b.grad)

#b.grad
#output.grad


RuntimeError: ignored

None of the tensors have 'requires_grad=True' 

**When to use this function**

A tensor can be created with requires_grad=True so that torch.autograd records operations on them for automatic differentiation.

## Function 4 

torch.bincount(input, weights=None, minlength=0) → Tensor

Count the frequency of each value in an array of non-negative ints.

In [0]:
# Example 1
x = torch.tensor([0,1,4,4])
torch.bincount(x)

tensor([1, 1, 0, 0, 2])

returns the count of each digit in the tensor

for eg 

2's count is 0

4's count is 2

In [0]:
# Example 2 
x = torch.tensor([],dtype=torch.int64)
torch.bincount(x,minlength=4)

tensor([0, 0, 0, 0])

If input is empty, then output is tensor of size minlength filled with zeros

In [3]:
# Example 3 - breaking (to illustrate when it breaks)
x =  torch.tensor([1.,2.,4.])
torch.bincount(x)

RuntimeError: ignored

The function returns the frequency of each value in an array of non-negative INTS

**When to use this function**

It can be used to count the frequency of each value in an array of non-negative ints


## Function 5 

torch.ceil(input, out=None) → Tensor

Returns a new tensor with the ceil of the elements of input, the smallest integer greater than or equal to each element.

In [0]:
# Example 1 
a = torch.randn(4)
print(a)
print("values after ceil: ",torch.ceil(a))

tensor([ 0.4786, -0.2044, -2.0745,  1.0624])
values after ceil:  tensor([ 1., -0., -2.,  2.])


rounds off the input values

In [0]:
# Example 2 
a = torch.tensor([1.4,-4.5,9.0])
torch.ceil(a)


tensor([ 2., -4.,  9.])

rounds off the input values

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([1,2,3,4])
torch.ceil(a)


RuntimeError: ignored

torch.ceil() works on float inputs


**When to use this function**

It can be used to calculate the ceil of given number of inputs of type flaot.



## Conclusion

AT THE END, I WOULD LIKE  TO SUMMARIZE WHAT WE HAVE COVERED SO FAR!

1. PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision, natural language processing etc.

2. We covered 5 functions of pytorch namely -

    * new_ones()

    * Torch.tensor.items()

    * Torch.auto_grad

    * Torch.bincount()

    * Torch.ceil()

## Reference Links
For more information about pytorch and tensors visit - 
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [0]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 3.6MB/s 


In [0]:
import jovian

In [0]:
a = torch.tensor([1,2,3], dtype = torch.float64)

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
